name: Workout Tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Installs dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Create build directory
        run: mkdir -p System/build

      - name: Configure CMake
        run: |
          cd System/build
          cmake ..

      - name: Build project
        run: |
          cd System/build
          make

      - name: Run tests
        run: |
          cd System/build
          ./linked-list-test --gtest_color=yes
